# Assignment 2: Data Parsing, Cleansing and Integration
## Task 3
#### Student Name: Prakash Sudarsan raj
#### Student ID: s4135999


Environment: Python 3 and Jupyter notebook

Libraries used: please include the main libraries you used in your assignment, e.g.,:
* pandas
* re
* numpy


## Introduction
This task focuses on integrating the cleaned dataset from Task 2 with the provided dataset2.csv file. The main challenge was that both datasets followed different schemas, even though they contained similar information.

To solve this, the schema differences were identified and resolved by renaming columns and aligning their structure. After that, both datasets were combined into a single table.

Finally, the integrated dataset was checked for duplicate records and consistency, and a suitable global key approach was discussed based on the nature of the data.

##  Import libraries

In [51]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
from pathlib import Path

In [52]:
base_path = Path(".")
dataset1_path = base_path / "S4135999_dataset1_solution.csv"
dataset2_path = base_path / "S4135999_dataset2.csv"

### 1. Examining and loading data
In this step, both datasets were loaded and examined to understand their structure.

The cleaned dataset from Task 2 contains review data extracted from XML, while dataset2.csv is already structured in a tabular format. By comparing their columns, it was observed that both datasets contain similar attributes but use different naming conventions.

This inspection helps identify schema conflicts before integration.

In [53]:
dataset1 = pd.read_csv(dataset1_path)
dataset2 = pd.read_csv(dataset2_path)

In [54]:
print("Dataset 1 shape:", dataset1.shape)
print("Dataset 2 shape:", dataset2.shape)

Dataset 1 shape: (6435, 11)
Dataset 2 shape: (7500, 11)

In [55]:
print("Dataset 1 columns:")
print(dataset1.columns.tolist())

print("\nDataset 2 columns:")
print(dataset2.columns.tolist())

Dataset 1 columns:
['ClothID', 'Age', 'Review Title', 'Customer Rating', 'Positive Review Count', 'Section', 'Department', 'Category', 'Online Time', 'Cost', 'Recommended IND']

Dataset 2 columns:
['Clothing ID', 'Age', 'Title', 'Rating', 'Recommended IND', 'Positive Feedback Count', 'Division Name', 'Department Name', 'Class Name', 'Active Time', 'Price']

In [56]:
dataset1.head()

,ClothID,Age,Review Title,Customer Rating,Positive Review Count,Section,Department,Category,Online Time,Cost,Recommended IND
0,892.0,39,So soft and figure-flattering,5,0,General,Tops,Fine gauge,10.761204,38.468108,1
1,867.0,28,"Great shirt, but don't expect it to last",3,0,General Petite,Tops,Knits,3.593713,47.803430,1
2,997.0,49,Beautiful!,5,0,General Petite,Bottoms,Skirts,5.445432,52.322641,1
3,1077.0,26,So much better in person,5,5,General,Dresses,Dresses,4.960395,73.037124,1
4,1033.0,35,Nope!,2,0,General,Bottoms,Jeans,21.308400,51.940232,0

In [57]:
dataset2.head()

,Clothing ID,Age,Title,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,Active Time,Price
0,1072,66,Navy print shirtdress,5,1,5,General,Dresses,Dresses,2.646142,129.953578
1,1121,27,Disappointed,2,0,1,General,Jackets,Outerwear,9.523176,75.462311
2,860,35,Beautiful color and flattering design,4,1,0,General,Tops,Knits,10.699384,68.872656
3,895,30,Cute!!,5,1,0,General,Tops,Fine gauge,10.902540,32.188964
4,426,29,So excited but then this,4,1,0,Initmates,Intimate,Lounge,11.592513,121.329391

### 2. Resolving schema conflicts
Before merging the datasets, schema conflicts need to be resolved. Although both datasets contain similar information, their column names and structures are different.

The conflicts mainly include naming differences, column ordering, and data type inconsistencies. These issues must be fixed so both datasets follow the same schema.

### Conflict 1: Naming conflicts
The cleaned dataset uses source-based column names such as "ClothID", "Review Title", and "Customer Rating", while dataset2 uses standardised names like "Clothing ID", "Title", and "Rating".

Since these columns represent the same information, they were renamed to match the global schema used in dataset2.

In [58]:
rename_map = {
    "ClothID": "Clothing ID",
    "Review Title": "Title",
    "Customer Rating": "Rating",
    "Positive Review Count": "Positive Feedback Count",
    "Section": "Division Name",
    "Department": "Department Name",
    "Category": "Class Name",
    "Online Time": "Active Time",
    "Cost": "Price"
}

dataset1_renamed = dataset1.rename(columns=rename_map)
dataset1_renamed.head()

,Clothing ID,Age,Title,Rating,Positive Feedback Count,Division Name,Department Name,Class Name,Active Time,Price,Recommended IND
0,892.0,39,So soft and figure-flattering,5,0,General,Tops,Fine gauge,10.761204,38.468108,1
1,867.0,28,"Great shirt, but don't expect it to last",3,0,General Petite,Tops,Knits,3.593713,47.803430,1
2,997.0,49,Beautiful!,5,0,General Petite,Bottoms,Skirts,5.445432,52.322641,1
3,1077.0,26,So much better in person,5,5,General,Dresses,Dresses,4.960395,73.037124,1
4,1033.0,35,Nope!,2,0,General,Bottoms,Jeans,21.308400,51.940232,0

### Conflict 2: Column order conflict
After renaming the columns, the order of columns in both datasets was still different.

To ensure consistency, both datasets were rearranged to follow the same column order based on the required global schema.

In [59]:
global_schema = [
    "Clothing ID",
    "Age",
    "Title",
    "Rating",
    "Recommended IND",
    "Positive Feedback Count",
    "Division Name",
    "Department Name",
    "Class Name",
    "Active Time",
    "Price"
]

In [60]:
dataset1_aligned = dataset1_renamed[global_schema]
dataset2_aligned = dataset2[global_schema]

In [61]:
print("Dataset 1 aligned columns:")
print(dataset1_aligned.columns.tolist())

print("\nDataset 2 aligned columns:")
print(dataset2_aligned.columns.tolist())

Dataset 1 aligned columns:
['Clothing ID', 'Age', 'Title', 'Rating', 'Recommended IND', 'Positive Feedback Count', 'Division Name', 'Department Name', 'Class Name', 'Active Time', 'Price']

Dataset 2 aligned columns:
['Clothing ID', 'Age', 'Title', 'Rating', 'Recommended IND', 'Positive Feedback Count', 'Division Name', 'Department Name', 'Class Name', 'Active Time', 'Price']

### Conflict 3: Data type consistency
Even after aligning column names and order, the data types needed to be consistent across both datasets.

Numeric columns such as ID, rating, and price were converted to appropriate numeric types to ensure compatibility during merging.

In [62]:
print("Dataset 1 data types:")
print(dataset1_aligned.dtypes)

print("\nDataset 2 data types:")
print(dataset2_aligned.dtypes)

Dataset 1 data types:
Clothing ID                float64
Age                          int64
Title                       object
Rating                       int64
Recommended IND              int64
Positive Feedback Count      int64
Division Name               object
Department Name             object
Class Name                  object
Active Time                float64
Price                      float64
dtype: object

Dataset 2 data types:
Clothing ID                  int64
Age                          int64
Title                       object
Rating                       int64
Recommended IND              int64
Positive Feedback Count      int64
Division Name               object
Department Name             object
Class Name                  object
Active Time                float64
Price                      float64
dtype: object

In [63]:
int_cols = [
    "Clothing ID",
    "Age",
    "Rating",
    "Recommended IND",
    "Positive Feedback Count"
]

float_cols = [
    "Active Time",
    "Price"
]

for col in int_cols:
    dataset1_aligned[col] = pd.to_numeric(dataset1_aligned[col], errors="coerce").astype("Int64")
    dataset2_aligned[col] = pd.to_numeric(dataset2_aligned[col], errors="coerce").astype("Int64")

for col in float_cols:
    dataset1_aligned[col] = pd.to_numeric(dataset1_aligned[col], errors="coerce")
    dataset2_aligned[col] = pd.to_numeric(dataset2_aligned[col], errors="coerce")

In [64]:
print("Dataset 1 updated data types:")
print(dataset1_aligned.dtypes)

print("\nDataset 2 updated data types:")
print(dataset2_aligned.dtypes)

Dataset 1 updated data types:
Clothing ID                  Int64
Age                          Int64
Title                       object
Rating                       Int64
Recommended IND              Int64
Positive Feedback Count      Int64
Division Name               object
Department Name             object
Class Name                  object
Active Time                float64
Price                      float64
dtype: object

Dataset 2 updated data types:
Clothing ID                  Int64
Age                          Int64
Title                       object
Rating                       Int64
Recommended IND              Int64
Positive Feedback Count      Int64
Division Name               object
Department Name             object
Class Name                  object
Active Time                float64
Price                      float64
dtype: object

### 3. Merging data
After resolving all schema conflicts, the two datasets were merged into one integrated dataset.

Since both datasets now share the same structure, vertical merging using concatenation was used. This combines all records from both datasets into a single table.

In [65]:
integrated_df = pd.concat([dataset1_aligned, dataset2_aligned], ignore_index=True)
integrated_df.head()

,Clothing ID,Age,Title,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,Active Time,Price
0,892,39,So soft and figure-flattering,5,1,0,General,Tops,Fine gauge,10.761204,38.468108
1,867,28,"Great shirt, but don't expect it to last",3,1,0,General Petite,Tops,Knits,3.593713,47.803430
2,997,49,Beautiful!,5,1,0,General Petite,Bottoms,Skirts,5.445432,52.322641
3,1077,26,So much better in person,5,1,5,General,Dresses,Dresses,4.960395,73.037124
4,1033,35,Nope!,2,0,0,General,Bottoms,Jeans,21.308400,51.940232

In [66]:
print("Integrated dataset shape:", integrated_df.shape)

Integrated dataset shape: (13935, 11)

### 4. Resolving data conflicts:
After merging the datasets, the integrated data was checked for data-level conflicts.

The main issue identified was duplicate records. These duplicates can occur when the same record appears in both datasets. Removing them ensures that the dataset contains only unique entries.

### Conflict 1: Duplicate records
Exact duplicate rows were identified where all values in the row are the same.

These duplicates were removed to avoid redundancy and maintain data quality in the final dataset.

In [67]:
exact_duplicates = integrated_df.duplicated()
print("Number of exact duplicate rows:", exact_duplicates.sum())

Number of exact duplicate rows: 153

In [68]:
integrated_df[exact_duplicates].head()

,Clothing ID,Age,Title,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,Active Time,Price
13735,892,39,So soft and figure-flattering,5,1,0,General,Tops,Fine gauge,10.761204,38.468108
13736,867,28,"Great shirt, but don't expect it to last",3,1,0,General Petite,Tops,Knits,3.593713,47.803430
13739,997,49,Beautiful!,5,1,0,General Petite,Bottoms,Skirts,5.445432,52.322641
13740,1077,26,So much better in person,5,1,5,General,Dresses,Dresses,4.960395,73.037124
13741,1033,35,Nope!,2,0,0,General,Bottoms,Jeans,21.308400,51.940232

In [69]:
integrated_df = integrated_df.drop_duplicates().reset_index(drop=True)
print("Shape after removing exact duplicates:", integrated_df.shape)

Shape after removing exact duplicates: (13782, 11)

### Conflict 2: Repeated Clothing ID values
It was observed that the same Clothing ID can appear multiple times. This is expected because multiple customers can review the same clothing item.

Therefore, repeated Clothing ID values were not treated as errors. Only exact duplicate rows were removed.

In [70]:
print("Number of unique Clothing ID values:", integrated_df["Clothing ID"].nunique())
print("Total number of rows:", len(integrated_df))

Number of unique Clothing ID values: 962
Total number of rows: 13782

In [71]:
integrated_df["Clothing ID"].value_counts().head(10)

1078    568
862     469
1094    447
1081    331
829     324
872     312
1110    297
868     248
895     230
867     226
Name: Clothing ID, dtype: Int64

#### Finding global key for the data
The dataset represents customer reviews rather than unique products. Therefore, a single column such as "Clothing ID" cannot act as a global key because it can have multiple associated reviews.

Instead, the uniqueness of the dataset is defined by the entire record. A composite key based on all columns can represent a unique review.

For this reason, duplicate handling was performed at the full-row level rather than relying on a single key column.

In [72]:
print("Duplicate rows after cleaning:", integrated_df.duplicated().sum())

Duplicate rows after cleaning: 0

In [73]:
candidate_key_check = integrated_df.duplicated(subset=global_schema).sum()
print("Duplicate count using all columns as composite key:", candidate_key_check)

Duplicate count using all columns as composite key: 0

### Handling Missing Values After Integration

After merging the datasets, some missing values were found in a few columns such as Title, Division Name, Department Name, and Class Name.

These missing values were not removed or replaced because they are very small compared to the total dataset size. Also, columns like Title are not critical for most analysis.

Removing rows would reduce the dataset unnecessarily, so the data was kept as it is after confirming that the missing values do not significantly affect the overall quality of the dataset.

After integration, additional validation checks were performed to ensure data quality.

First, summary statistics were examined to confirm that numeric values such as Age, Rating, and Price fall within reasonable ranges.

Second, categorical columns such as Division Name, Department Name, and Class Name were reviewed to ensure consistency and absence of unexpected values.

Finally, missing values were assessed and found to be minimal relative to the dataset size. Since they do not significantly affect analysis, no imputation or removal was performed.

These validation steps confirm that the integrated dataset is reliable and suitable for further analysis.

### 5. Saving the integrated and reshaped data
The final integrated dataset was saved as a CSV file using the required naming format for submission.

In [74]:
integrated_df.to_csv("S4135999_dataset_integrated.csv", index=False)
print("File saved successfully: S4135999_dataset_integrated.csv")

File saved successfully: S4135999_dataset_integrated.csv

In [75]:
print(integrated_df.shape)
print(integrated_df.isna().sum())
print(integrated_df.dtypes)
integrated_df.head()

(13782, 11)
Clothing ID                   0
Age                           0
Title                      1208
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                 6
Department Name               6
Class Name                    6
Active Time                   0
Price                         0
dtype: int64
Clothing ID                  Int64
Age                          Int64
Title                       object
Rating                       Int64
Recommended IND              Int64
Positive Feedback Count      Int64
Division Name               object
Department Name             object
Class Name                  object
Active Time                float64
Price                      float64
dtype: object

,Clothing ID,Age,Title,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,Active Time,Price
0,892,39,So soft and figure-flattering,5,1,0,General,Tops,Fine gauge,10.761204,38.468108
1,867,28,"Great shirt, but don't expect it to last",3,1,0,General Petite,Tops,Knits,3.593713,47.803430
2,997,49,Beautiful!,5,1,0,General Petite,Bottoms,Skirts,5.445432,52.322641
3,1077,26,So much better in person,5,1,5,General,Dresses,Dresses,4.960395,73.037124
4,1033,35,Nope!,2,0,0,General,Bottoms,Jeans,21.308400,51.940232

## Summary of the Assessment Task
Give a short summary and anything you would like to talk about this assessment task here.